### ISSUE TITLE
Broken hyperlinks in P1 (items 60 and 62)

### ISSUE THREAD

**Issue by neurochatter** [kavli-ntnu/MINI2P_toolbox#9]
In the P1 shopping list PDF, the hyperlinks associated with Item ID 60 and 62 point to internal NTNU links. I believe these links should point to Thorlabs products as follows:
Item 60: Manual Rotation Stage (RP03/M): https://www.thorlabs.com/thorproduct.cfm?partnumber=RP03/M
Item 62: Optical post (TR75/M): https://www.thorlabs.com/thorproduct.cfm?partnumber=TR75/M

**Comment by NathanielHorne** [comment]
There are also a few broken hyperlinks on the D0166 lens, the DMSP0405 dichroic mirror, and the D0213-3X, D0254-3X, and D0277-3X objectives (items 109 - 113).
These links are broken in the sense that the links to these components lead to the homepages of the various companies they are manufactured by instead of their respective component pages.

**Comment by marinesrj** [comment]
Thank you for the corrections and suggestions. We will update the links as soon as possible in P1.
The broken hyperlinks were raised to the company main webpage, as some of them were not available in their products list because they are custom-made. However, we are going to share shortly documents with all miniature objectives, for example.
